export default function Home() {
	return (
		<main>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>
			<h2>Content</h2>v
		</main>
	)
}
